version: "2"
services:
    renovate-controller:
        build: .
        container_name: renovate-controller
        volumes:
            - ./renovate:/home/renovate/config
        ports:
            - "80:8080"

networks:
    default:
        driver: bridge
